# Generated by Django 5.2.7 on 2026-04-21 13:47

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0015_alter_producto_imagen'),
    ]

    operations = [
        migrations.CreateModel(
            name='DocumentoBiblioteca',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numero_documento', models.CharField(editable=False, max_length=20, unique=True)),
                ('titulo', models.CharField(max_length=200)),
                ('descripcion', models.TextField()),
                ('link_descarga', models.URLField(max_length=500)),
                ('fecha', models.DateTimeField(auto_now_add=True)),
                ('universidad', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='documentos', to='app.universidad')),
            ],
        ),
    ]
