# Generated by Django 5.2.7 on 2026-04-21 15:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0016_documentobiblioteca'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='documentobiblioteca',
            name='link_descarga',
        ),
        migrations.AddField(
            model_name='documentobiblioteca',
            name='archivo',
            field=models.FileField(blank=True, null=True, upload_to='biblioteca/'),
        ),
    ]
