# Generated by Django 5.2.7 on 2026-05-06 19:56

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0020_aviso_util'),
    ]

    operations = [
        migrations.AlterField(
            model_name='documentobiblioteca',
            name='universidad',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='documentos', to='app.universidad'),
        ),
    ]
